pipeline {
    agent {
        docker { 
            image 'hamzasamara/ubuntu-file-image'
            args '-u root' // Run the container as root
        }
    }
    stages {
        stage('Check Operating System') {
            steps {
                sh 'uname -a'
            }
        }
    
        stage('Check The User') {
            steps {
                sh 'whoami'
            }
        }
    
        stage('Display Disk and RAM Usage') {
            steps {
                sh 'df -h'   // Display disk usage
                sh 'free -m' // Display RAM usage
            }
        }
        stage('List Running Processes') {
            steps {
                sh 'ps aux'
            }
        }
    }
}
